# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion_breve', models.TextField(blank=True, max_length=500)),
                ('telefono', models.CharField(max_length=20)),
                ('sitio_web', models.CharField(blank=True, max_length=140, null=True)),
                ('facebook', models.CharField(blank=True, max_length=140, null=True)),
                ('logo', models.ImageField(default='imagenes/ongs/default.png', upload_to='imagenes/ongs')),
                ('persona_responsable', models.CharField(max_length=140)),
                ('moyor_edad', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='ong',
            name='tipo_entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ong.TipoEntidad'),
        ),
        migrations.AddField(
            model_name='ong',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
